import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { CartProvider } from "../contexts/CartContext";
import { ReactNode } from "react";
import { OrderProvider } from "@/contexts/OrderContext"; //향후 특정 화면으로 이동하도록 수정

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <OrderProvider>
          <CartProvider>{children}</CartProvider>
        </OrderProvider>
      </body>
    </html>
  );
}